CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    discovery_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score INT NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    discovery_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_email, discovery_id)
);
